# Generated by Django 4.1.7 on 2023-03-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrariaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='livraria/'),
        ),
    ]
